export const dom = {
  searchBtn: document.getElementById('searchBtn'),
  areaBtn: document.getElementById('areaBtn'),
  siteSelect: document.getElementById('siteSelect'),
  searchInput: document.getElementById('searchInput'),
  areaInput: document.getElementById('areaInput'),
  filterBar: document.getElementById('filter-bar'),
  filterInput: document.getElementById('filterInput'),
  filterBtn: document.getElementById('filterBtn'),
  filterChips: document.getElementById('filter-chips'),
  status: document.getElementById('status'),
  selectedOutput: document.getElementById('selected-output'),
  contentLayout: document.getElementById('content-layout'),
  profilesContainer: document.getElementById('profiles-container'),
  profileDetailsContainer: document.getElementById('profile-details-container'),
  imagesContainer: document.getElementById('images-container'),
  favoritesContainer: document.getElementById('favorites-container'),
  areaDropdownWrap: document.getElementById('area-dropdown-wrap'),
  areaDropdownBtn: document.getElementById('areaDropdownBtn'),
  areaDropdownPanel: document.getElementById('areaDropdownPanel'),
  tagDropdownWrap: document.getElementById('tag-dropdown-wrap'),
  tagDropdownBtn: document.getElementById('tagDropdownBtn'),
  tagDropdownPanel: document.getElementById('tagDropdownPanel'),
  redvelvetDetailFilters: document.getElementById('redvelvet-detail-filters'),
  ageMinInput: document.getElementById('ageMinInput'),
  ageMaxInput: document.getElementById('ageMaxInput'),
  bustInput: document.getElementById('bustInput'),
};
